"""
OpenAI Code Interpreter File Proxy Example

This example demonstrates how to use the file proxy system to handle
downloadable files generated by OpenAI's Code Interpreter tool.

Requirements:
    - OPENAI_API_KEY set in .env file
    - FastAPI server running (main.py)
    - openai-agents package installed

Usage:
    1. Start the FastAPI server: python main.py
    2. Run this example: python examples/file_proxy_example.py
"""

import asyncio
import json
import os
from dotenv import load_dotenv
from openai import OpenAI
from agents import Runner, Agent, CodeInterpreterTool

# Import file proxy utilities
from trading_agent_tp.utils.file_proxy import (
    collect_file_refs,
    replace_sandbox_links,
    extract_text_from_response,
    process_agent_response
)

# Load environment
load_dotenv()

# Initialize OpenAI client
client = OpenAI()

# Backend base URL (where your FastAPI app is running)
BACKEND_BASE = os.getenv("FILE_PROXY_BASE_URL", "http://localhost:8888/api/files/download")


async def example_basic_usage():
    """
    Basic example: Create an agent with CodeInterpreterTool and process file outputs.
    """
    print("\n" + "=" * 80)
    print("EXAMPLE 1: Basic File Proxy Usage")
    print("=" * 80)

    # Create an agent with CodeInterpreterTool
    agent = Agent(
        name="DataAnalystAgent",
        tools=[
            CodeInterpreterTool(
                tool_config={
                    "type": "code_interpreter",
                    "container": {"type": "auto"}
                }
            )
        ],
        instructions="""
        You are a data analyst agent. You can use the code interpreter tool to:
        - Generate charts and visualizations
        - Create PDF reports
        - Export data to CSV/Excel
        - Perform data analysis

        When generating files, always provide them as downloadable links.
        """,
        model="gpt-4.1-mini",
    )

    # Create runner
    runner = Runner()

    # Run the agent with a request to generate a file
    user_input = "Create a simple line chart showing trading volume data for BTC over the last week. Export it as a PNG file."

    print(f"\n📤 User Input: {user_input}")
    print("\n⏳ Running agent...")

    result = await runner.run(agent, user_input)
    response = result.raw_responses[0]

    # Process the response using file proxy utilities
    processed = process_agent_response(response, BACKEND_BASE)

    print("\n✅ Agent Response (with working file links):")
    print("-" * 80)
    print(processed["text"])
    print("-" * 80)

    print("\n📎 File References:")
    print(json.dumps(processed["file_refs"], indent=2))


async def example_manual_processing():
    """
    Manual example: Step-by-step processing of agent response.
    """
    print("\n" + "=" * 80)
    print("EXAMPLE 2: Manual Step-by-Step Processing")
    print("=" * 80)

    # Create agent
    agent = Agent(
        name="ReportGeneratorAgent",
        tools=[
            CodeInterpreterTool(
                tool_config={
                    "type": "code_interpreter",
                    "container": {"type": "auto"}
                }
            )
        ],
        instructions="Generate professional reports and export them as PDF files.",
        model="gpt-4.1-mini",
    )

    runner = Runner()

    # Run agent
    user_input = "Create a professional PDF report about cryptocurrency market trends. Include a title page and summary."

    print(f"\n📤 User Input: {user_input}")
    print("\n⏳ Running agent...")

    result = await runner.run(agent, user_input)
    response = result.raw_responses[0]

    # Step 1: Extract text content
    print("\n📝 Step 1: Extracting text content...")
    text = extract_text_from_response(response)
    print(f"Extracted {len(text)} characters")

    # Step 2: Collect file references
    print("\n📁 Step 2: Collecting file references...")
    file_refs = collect_file_refs(response)
    print(f"Found {len(file_refs)} file(s)")

    for i, ref in enumerate(file_refs, 1):
        print(f"  File {i}:")
        print(f"    - Filename: {ref['filename']}")
        print(f"    - File ID: {ref['file_id']}")
        print(f"    - Container: {ref['container_id']}")

    # Step 3: Replace sandbox links
    print("\n🔗 Step 3: Replacing sandbox links with proxy URLs...")
    final_text = replace_sandbox_links(text, file_refs, BACKEND_BASE)

    print("\n✅ Final output:")
    print("-" * 80)
    print(final_text)
    print("-" * 80)


async def example_trading_analysis():
    """
    Trading-specific example: Generate technical analysis report with charts.
    """
    print("\n" + "=" * 80)
    print("EXAMPLE 3: Trading Analysis with File Generation")
    print("=" * 80)

    # Create a specialized trading analysis agent
    agent = Agent(
        name="TechnicalAnalysisAgent",
        tools=[
            CodeInterpreterTool(
                tool_config={
                    "type": "code_interpreter",
                    "container": {"type": "auto"}
                }
            )
        ],
        instructions="""
        You are a technical analysis expert. You can:
        - Generate candlestick charts
        - Create indicator visualizations (RSI, MACD, Bollinger Bands)
        - Export analysis reports as PDF
        - Create data exports in CSV format

        Always provide downloadable files for your outputs.
        """,
        model="gpt-4o-mini",
    )

    runner = Runner()

    # Run analysis
    user_input = """
    Perform a technical analysis simulation:
    1. Generate a candlestick chart showing BTC price movement
    2. Add RSI and MACD indicators
    3. Export the chart as PNG
    4. Create a summary report as PDF
    """

    print(f"\n📤 User Input: {user_input}")
    print("\n⏳ Running technical analysis...")

    result = await runner.run(agent, user_input)
    response = result.raw_responses[0]

    # Process response
    processed = process_agent_response(response, BACKEND_BASE)

    print("\n✅ Analysis Complete!")
    print("-" * 80)
    print(processed["text"])
    print("-" * 80)

    if processed["file_refs"]:
        print("\n📊 Generated Files:")
        for i, ref in enumerate(processed["file_refs"], 1):
            download_url = f"{BACKEND_BASE}/{ref['container_id']}/{ref['file_id']}/{ref['filename']}"
            print(f"  {i}. {ref['filename']}")
            print(f"     Download: {download_url}")


async def main():
    """
    Run all examples.
    """
    print("\n" + "=" * 80)
    print("OpenAI Code Interpreter File Proxy - Examples")
    print("=" * 80)
    print("\nMake sure your FastAPI server is running at http://localhost:8888")
    print("Press Ctrl+C to exit\n")

    try:
        # Run examples
        await example_basic_usage()
        await example_manual_processing()
        await example_trading_analysis()

        print("\n" + "=" * 80)
        print("All examples completed successfully!")
        print("=" * 80)

    except KeyboardInterrupt:
        print("\n\n⚠️ Examples interrupted by user")
    except Exception as e:
        print(f"\n\n❌ Error occurred: {str(e)}")
        import traceback
        traceback.print_exc()


if __name__ == "__main__":
    asyncio.run(main())
