"""
OpenAI Container File Proxy API Endpoints

This module provides FastAPI endpoints for proxying file downloads from
OpenAI's Code Interpreter containers to frontend clients.

When agents use CodeInterpreterTool to generate files, those files are stored
in OpenAI's containers and not directly accessible. This endpoint acts as a
secure proxy to fetch and serve those files.

Endpoint: GET /api/files/download/{container_id}/{file_id}/{filename}

Example:
    http://localhost:8888/api/files/download/cntr_xyz789/cfile_abc123/report.pdf
"""

import os
import logging
from datetime import datetime
from typing import Optional
from urllib.parse import urlparse
import re

import requests
from fastapi import APIRouter, Response, HTTPException
from pydantic import BaseModel
from dotenv import load_dotenv

# Load environment variables
load_dotenv()

# Configure logging
logger = logging.getLogger(__name__)

# Create router
router = APIRouter(
    prefix="/api/v1/files",
    tags=["file-proxy"],
    responses={404: {"description": "File not found"}},
)

# OpenAI API configuration
OPENAI_API_KEY = os.getenv("OPENAI_API_KEY")

if not OPENAI_API_KEY:
    logger.warning("⚠️ OPENAI_API_KEY not found in environment. File proxy will not work.")

HEADERS = {
    "Authorization": f"Bearer {OPENAI_API_KEY}"
}


class ProxyUrlRequest(BaseModel):
    """Request model for generic URL proxy endpoint."""
    url: str
    filename: Optional[str] = None


@router.get("/download/{container_id}/{file_id}/{filename}")
async def download_file(
    container_id: str,
    file_id: str,
    filename: str = "output.bin"
) -> Response:
    """
    Proxy endpoint to download a file from an OpenAI Code Interpreter container.

    This endpoint fetches files generated by the CodeInterpreterTool and serves
    them to the client with appropriate headers for download.

    Args:
        container_id: The OpenAI container identifier (e.g., 'cntr_xyz789')
        file_id: The file identifier within the container (e.g., 'cfile_abc123')
        filename: The desired filename for download (default: 'output.bin')

    Returns:
        Response: File content with appropriate headers for download

    Raises:
        HTTPException: 404 if file not found or API error occurs

    Example:
        GET /api/files/download/cntr_xyz789/cfile_abc123/analysis.pdf
    """
    timestamp = datetime.now().strftime("%H:%M:%S")
    url = f"https://api.openai.com/v1/containers/{container_id}/files/{file_id}/content"

    logger.info("=" * 80)
    logger.info(f"[{timestamp}] 📥 Incoming file download request")
    logger.info(f"Container ID : {container_id}")
    logger.info(f"File ID      : {file_id}")
    logger.info(f"Filename     : {filename}")
    logger.info(f"OpenAI URL   : {url}")
    logger.info(f"API Key set  : {'✅ Yes' if OPENAI_API_KEY else '❌ No'}")

    if not OPENAI_API_KEY:
        logger.error(f"[{timestamp}] ❌ OPENAI_API_KEY not configured")
        raise HTTPException(
            status_code=500,
            detail="OpenAI API key not configured. Please set OPENAI_API_KEY in environment."
        )

    try:
        # Fetch file from OpenAI API
        resp = requests.get(url, headers=HEADERS, timeout=30)

        logger.info(f"[{timestamp}] 🔍 Response status: {resp.status_code}")

        if resp.status_code != 200:
            logger.error(f"[{timestamp}] ❌ Response error: {resp.text}")
            raise HTTPException(
                status_code=resp.status_code,
                detail=f"Failed to fetch file from OpenAI: {resp.text}"
            )

        resp.raise_for_status()

        # Get file content
        data = resp.content
        size_kb = len(data) / 1024

        logger.info(f"[{timestamp}] ✅ File downloaded successfully ({size_kb:.2f} KB)")
        logger.info("=" * 80)

        # Determine content type based on filename extension
        content_type = _get_content_type(filename)

        # Return file with appropriate headers
        headers = {
            "Content-Disposition": f'attachment; filename="{filename}"',
            "Content-Type": content_type,
        }

        return Response(
            content=data,
            media_type=content_type,
            headers=headers
        )

    except requests.RequestException as e:
        logger.error(f"[{timestamp}] ❌ Request exception: {str(e)}")
        logger.info("=" * 80)
        raise HTTPException(
            status_code=502,
            detail=f"Error fetching file from OpenAI: {str(e)}"
        )
    except Exception as e:
        logger.error(f"[{timestamp}] ❌ Unexpected error: {str(e)}")
        logger.info("=" * 80)
        raise HTTPException(
            status_code=500,
            detail=f"Unexpected error: {str(e)}"
        )


@router.post("/proxy-url")
async def proxy_url(request: ProxyUrlRequest) -> Response:
    """
    Generic URL proxy endpoint that accepts any sandbox or OpenAI file URL.

    This endpoint handles URLs from agent responses that may not have been
    processed with proper container_id/file_id metadata. It detects sandbox
    URLs and proxies them appropriately.

    Supported URL patterns:
    - sandbox:/mnt/data/filename.ext
    - https://ngoc.quanda1102.io.vn/mnt/data/filename.ext
    - https://[domain]/mnt/data/filename.ext
    - Direct OpenAI container URLs

    Args:
        request: ProxyUrlRequest containing the URL to proxy and optional filename

    Returns:
        Response: File content with appropriate download headers

    Raises:
        HTTPException: 400 for invalid URLs, 500 for proxy errors

    Example:
        POST /api/v1/files/proxy-url
        {
            "url": "https://ngoc.quanda1102.io.vn/mnt/data/report.pdf",
            "filename": "report.pdf"
        }
    """
    timestamp = datetime.now().strftime("%H:%M:%S")
    original_url = request.url

    logger.info("=" * 80)
    logger.info(f"[{timestamp}] 🌐 Generic URL proxy request")
    logger.info(f"Original URL: {original_url}")

    if not OPENAI_API_KEY:
        logger.error(f"[{timestamp}] ❌ OPENAI_API_KEY not configured")
        raise HTTPException(
            status_code=500,
            detail="OpenAI API key not configured. Please set OPENAI_API_KEY in environment."
        )

    # Extract filename from URL if not provided
    filename = request.filename
    if not filename:
        # Try to extract from URL path
        parsed = urlparse(original_url)
        path_parts = parsed.path.split("/")
        filename = path_parts[-1] if path_parts else "download.bin"
        logger.info(f"Extracted filename: {filename}")

    # Detect and transform sandbox URLs
    target_url = original_url

    # Pattern 1: sandbox:/mnt/data/filename
    if original_url.startswith("sandbox:"):
        # This is a local sandbox reference, we can't proxy it directly
        # It needs container_id and file_id which we don't have
        logger.error(f"[{timestamp}] ❌ Cannot proxy local sandbox:// URLs without metadata")
        raise HTTPException(
            status_code=400,
            detail="Local sandbox:// URLs require container_id and file_id. Use the /download endpoint instead."
        )

    # Pattern 2 & 3: https://[domain]/mnt/data/filename
    # This is actually a proxy URL, not a direct OpenAI URL
    # We need to detect if it's an OpenAI container URL or a sandbox proxy URL
    if "/mnt/data/" in original_url:
        logger.warning(f"[{timestamp}] ⚠️  URL contains /mnt/data/ path - this appears to be a sandbox URL")
        logger.warning("Without container_id and file_id, we cannot fetch this file from OpenAI")
        raise HTTPException(
            status_code=400,
            detail="Sandbox URLs with /mnt/data/ path require container_id and file_id metadata. "
                   "This file cannot be proxied without additional information."
        )

    # Pattern 4: Direct OpenAI container URL
    # https://api.openai.com/v1/containers/{container_id}/files/{file_id}/content
    if "api.openai.com" in original_url and "/containers/" in original_url:
        target_url = original_url
        logger.info(f"Direct OpenAI container URL detected")
    else:
        # Unknown URL pattern - try to fetch it directly
        logger.info(f"Unknown URL pattern, attempting direct fetch")
        target_url = original_url

    logger.info(f"Target URL: {target_url}")

    try:
        # Fetch the file
        # For OpenAI URLs, use authorization; for others, try without
        headers = HEADERS if "api.openai.com" in target_url else {}

        resp = requests.get(target_url, headers=headers, timeout=30)

        logger.info(f"[{timestamp}] 🔍 Response status: {resp.status_code}")

        if resp.status_code != 200:
            logger.error(f"[{timestamp}] ❌ Response error: {resp.text}")
            raise HTTPException(
                status_code=resp.status_code,
                detail=f"Failed to fetch file: {resp.text}"
            )

        # Get file content
        data = resp.content
        size_kb = len(data) / 1024

        logger.info(f"[{timestamp}] ✅ File downloaded successfully ({size_kb:.2f} KB)")
        logger.info("=" * 80)

        # Determine content type
        content_type = _get_content_type(filename)

        # Return file with appropriate headers
        response_headers = {
            "Content-Disposition": f'attachment; filename="{filename}"',
            "Content-Type": content_type,
        }

        return Response(
            content=data,
            media_type=content_type,
            headers=response_headers
        )

    except requests.RequestException as e:
        logger.error(f"[{timestamp}] ❌ Request exception: {str(e)}")
        logger.info("=" * 80)
        raise HTTPException(
            status_code=502,
            detail=f"Error fetching file: {str(e)}"
        )
    except Exception as e:
        logger.error(f"[{timestamp}] ❌ Unexpected error: {str(e)}")
        logger.info("=" * 80)
        raise HTTPException(
            status_code=500,
            detail=f"Unexpected error: {str(e)}"
        )


@router.get("/health")
async def health_check() -> dict:
    """
    Health check endpoint for the file proxy service.

    Returns:
        dict: Service status and configuration info

    Example:
        GET /api/v1/files/health
    """
    return {
        "service": "file-proxy",
        "status": "healthy",
        "api_key_configured": bool(OPENAI_API_KEY),
        "endpoints": {
            "download": "/api/v1/files/download/{container_id}/{file_id}/{filename}",
            "proxy-url": "/api/v1/files/proxy-url",
            "health": "/api/v1/files/health"
        }
    }


def _get_content_type(filename: str) -> str:
    """
    Determine the MIME type based on file extension.

    Args:
        filename: The filename with extension

    Returns:
        str: MIME type string

    Example:
        >>> _get_content_type("report.pdf")
        "application/pdf"
    """
    extension = filename.lower().split(".")[-1] if "." in filename else ""

    content_types = {
        "pdf": "application/pdf",
        "png": "image/png",
        "jpg": "image/jpeg",
        "jpeg": "image/jpeg",
        "gif": "image/gif",
        "csv": "text/csv",
        "txt": "text/plain",
        "json": "application/json",
        "xlsx": "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
        "xls": "application/vnd.ms-excel",
        "docx": "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
        "doc": "application/msword",
        "zip": "application/zip",
        "html": "text/html",
        "xml": "application/xml",
    }

    return content_types.get(extension, "application/octet-stream")