"""
OpenAI Code Interpreter File Proxy Utilities

This module provides utilities for handling downloadable files generated by
OpenAI's hosted Code Interpreter (via the CodeInterpreterTool).

When the hosted tool returns sandbox links like:
    [Download file.pdf](sandbox:/mnt/data/file.pdf)

These links are not directly accessible to frontend users. This module:
1. Extracts container_file_citation annotations from agent responses
2. Replaces sandbox URLs with backend proxy URLs

Example:
    from trading_agent_tp.utils.file_proxy import collect_file_refs, replace_sandbox_links

    # After running an agent with CodeInterpreterTool
    refs = collect_file_refs(response)
    markdown_output = replace_sandbox_links(original_text, refs, backend_base)
"""

import re
import os
from typing import List, Dict, Any, Optional


def get_backend_base_url() -> str:
    """
    Get the file download base URL for file proxying.

    Priority:
    1. FILE_PROXY_BASE_URL (custom override)
    2. FRONTEND_URL + /api/v1/files/download (recommended for production)
    3. Default to Next.js dev server (http://localhost:3000/api/v1/files/download)

    Returns:
        str: The file proxy base URL

    Example:
        Development: http://localhost:3000/api/v1/files/download
        Production: https://your-frontend.com/api/v1/files/download
    """
    # Check for explicit override
    explicit_url = os.getenv("FILE_PROXY_BASE_URL")
    if explicit_url:
        return explicit_url.rstrip("/")

    # Use FRONTEND_URL if available (recommended)
    frontend_url = os.getenv("FRONTEND_URL")
    if frontend_url:
        return f"{frontend_url.rstrip('/')}/api/v1/files/download"

    # Default to Next.js development server
    return "http://localhost:3000/api/v1/files/download"


def collect_file_refs(model_response: Any) -> List[Dict[str, str]]:
    """
    Extract container_file_citation entries from an OpenAI model response.

    This function traverses the model response structure to find all file
    citations generated by the Code Interpreter tool.

    Args:
        model_response: The raw response object from an OpenAI agent run

    Returns:
        List[Dict[str, str]]: List of file references, each containing:
            - file_id: The OpenAI file identifier
            - filename: The name of the file
            - container_id: The container identifier where the file is stored

    Example:
        >>> refs = collect_file_refs(response)
        >>> print(refs)
        [
            {
                "file_id": "cfile_abc123",
                "filename": "analysis.pdf",
                "container_id": "cntr_xyz789"
            }
        ]
    """
    refs = []

    # Navigate through the response structure
    for output in getattr(model_response, "output", []) or []:
        for content in getattr(output, "content", []) or []:
            for ann in getattr(content, "annotations", []) or []:
                if getattr(ann, "type", None) == "container_file_citation":
                    refs.append({
                        "file_id": ann.file_id,
                        "filename": ann.filename,
                        "container_id": ann.container_id
                    })

    return refs


def replace_sandbox_links(
    text: str,
    refs: List[Dict[str, str]],
    backend_base: Optional[str] = None
) -> str:
    """
    Replace sandbox URLs with backend proxy URLs in markdown format.

    This function finds all sandbox:// links and HTTPS sandbox URLs in the text
    and replaces them with working URLs that point to your backend proxy endpoint.

    Args:
        text: The markdown text containing sandbox links
        refs: List of file references from collect_file_refs()
        backend_base: Optional backend base URL. If not provided, uses default

    Returns:
        str: The text with sandbox links replaced by proxy URLs

    Example:
        Original text:
            "Download the report: [Download file.pdf](sandbox:/mnt/data/file.pdf)"
            "Or: [file.pdf](https://ngoc.quanda1102.io.vn/mnt/data/file.pdf)"

        After replacement:
            "Download the report: [file.pdf](http://localhost:8888/api/v1/files/download/cntr_xyz/cfile_abc/file.pdf)"
            "Or: [file.pdf](http://localhost:8888/api/v1/files/download/cntr_xyz/cfile_abc/file.pdf)"
    """
    if not text or not refs:
        return text

    if backend_base is None:
        backend_base = get_backend_base_url()

    for r in refs:
        # Construct the proxy URL with container_id, file_id, and filename
        proxy_url = f"{backend_base}/{r['container_id']}/{r['file_id']}/{r['filename']}"
        filename = r['filename']

        # Pattern 1: Replace sandbox:// markdown links
        # Matches: [Download ...](sandbox:/mnt/data/...)
        text = re.sub(
            r"\[Download[^\]]*\]\(sandbox:[^)]+\)",
            f"[{filename}]({proxy_url})",
            text
        )

        # Pattern 2: Replace sandbox:// links without "Download" prefix
        # Matches: [anything](sandbox:/mnt/data/...)
        text = re.sub(
            r"\[[^\]]*\]\(sandbox:/mnt/data/[^)]*\)",
            f"[{filename}]({proxy_url})",
            text
        )

        # Pattern 3: Replace HTTPS sandbox URLs from agents framework
        # Matches: [anything](https://ngoc.quanda1102.io.vn/mnt/data/...)
        # or any similar sandbox domain pattern
        text = re.sub(
            r"\[[^\]]*\]\(https://[a-zA-Z0-9\-\.]+\.io\.vn/mnt/data/[^)]*\)",
            f"[{filename}]({proxy_url})",
            text
        )

        # Pattern 4: Replace HTTPS sandbox URLs with any sandbox domain
        # Matches: [anything](https://.../mnt/data/filename)
        # This is more specific - only replace if filename matches
        text = re.sub(
            rf"\[[^\]]*\]\(https://[^)]+/mnt/data/{re.escape(filename)}\)",
            f"[{filename}]({proxy_url})",
            text
        )

        # Pattern 5: Replace bare HTTPS sandbox URLs (not in markdown)
        # Useful for plain text URLs
        text = re.sub(
            rf"https://[a-zA-Z0-9\-\.]+\.io\.vn/mnt/data/{re.escape(filename)}",
            proxy_url,
            text
        )

    return text


def extract_text_from_response(model_response: Any) -> str:
    """
    Extract all text content from an OpenAI model response.

    Args:
        model_response: The raw response object from an OpenAI agent run

    Returns:
        str: Combined text content from all output blocks

    Example:
        >>> text = extract_text_from_response(response)
        >>> print(text)
        "Here is your analysis... [Download report.pdf](sandbox:/mnt/data/report.pdf)"
    """
    markdown_output = ""

    for output in getattr(model_response, "output", []) or []:
        for content in getattr(output, "content", []) or []:
            if hasattr(content, "text"):
                markdown_output += content.text + "\n"

    return markdown_output.strip()


def process_agent_response(
    model_response: Any,
    backend_base: Optional[str] = None
) -> Dict[str, Any]:
    """
    Complete processing of an agent response with file handling.

    This is a convenience function that combines all the file proxy operations:
    1. Extracts text content
    2. Collects file references
    3. Replaces sandbox links

    Args:
        model_response: The raw response object from an OpenAI agent run
        backend_base: Optional backend base URL

    Returns:
        Dict containing:
            - text: The processed markdown text with working file links
            - file_refs: List of file references

    Example:
        >>> result = process_agent_response(response)
        >>> print(result["text"])
        >>> print(result["file_refs"])
    """
    # Extract text content
    text = extract_text_from_response(model_response)

    # Collect file references
    file_refs = collect_file_refs(model_response)

    # Replace sandbox links with proxy URLs
    processed_text = replace_sandbox_links(text, file_refs, backend_base)

    return {
        "text": processed_text,
        "file_refs": file_refs
    }